### ISSUE TITLE
"Authorization Extension: Blocked event loop" error

### ISSUE THREAD

**Issue by Tyf0x** [auth0/auth0-authorization-extension#165]
Hi,

for a little while now, we receive an "Authorization Extension: Blocked event loop" exception when login-in our system. This is happening on all our accounts from dev to prod.

An [auth0 community question has been asked](https://community.auth0.com/questions/8813/authorization-extension-blocked-event-loop-when-si) and it seems we are not the only ones seeing the issue.
It seems it is not only limited to login actions, but also user creation, at least.

Any info, insight or workaround?

Thank you

**Comment by manujadev** [comment]
Experiencing the same issue. Look forward hearing of a fix soon.

**Comment by Tyf0x** [comment]
This error still happens to us on a regular basis. Any update @auth0 team?

**Comment by colleenfeng** [comment]
This error happens to us regularly, too. It's been 18 days since the ticket was opened, any update?

**Comment by duhseekoh** [comment]
Can verify it happens randomly on any request to the authorization api. Sometimes its on login, sometimes its adding a member to a group, etc...

**Comment by Gilthoniel** [comment]
Same here, it would be great to have a hint about it.

**Comment by kadeempardue** [comment]
Same here. Would love an update from the Auth0 team.

**Comment by duhseekoh** [comment]
Auth0 support @jmangelo responded here: https://community.auth0.com/questions/8813/authorization-extension-blocked-event-loop-when-si?childToView=9998#comment-9998

**Comment by noamt** [comment]
We're suffering from this issue as well and would love to see this resolved

**Comment by MrMint** [comment]
we are running into this issue as well.

**Comment by shusson** [comment]
Experiencing the same issue

**Comment by saltukalakus** [comment]
Hi, we (Auth0) are working on this issue. A fix has been implemented. We will update with the ETA on when it will hit the production and the development tenants as soon as we have it.

**Comment by vlood** [comment]
@saltukalakus , could you confirm that the issue is resolved? I experienced it back then when the rest of the guys here were reporting it, but now I can't reproduce the problem anymore. Still a word from the developers confirming it's all good would be nice.

**Comment by Tyf0x** [comment]
This issue seems to be resolved: [auth0 forum thread](https://community.auth0.com/answers/12050/view)
I'll close the issue.

**Comment by mhertis** [comment]
We are still experiencing this issue in EU tenant.

**Comment by reintjanhoiting** [comment]
We are still experiencing this exact issue. (last occurred, Jan 2nd 2018)

**Comment by danloiterton** [comment]
We seem to be experiencing this issue as of this morning (EU)

**Comment by ernie-suplari** [comment]
We just experienced this error.

**Comment by niwsa** [comment]
Experiencing this error in US tenant
```Could not get a new token (unauthorized: Authorization Extension: Blocked event loop).```

**Comment by cmmills91** [comment]
We still see this error about 3 times a day (that we know about) on a US Tenant....

**Comment by michal-rychlik** [comment]
We still see this around 5 times a day. Can you please reopen and act?

Is it connected to the recent Node 4 deprecation?

**Comment by pidov** [comment]
@Tyf0x still happening

**Comment by Tyf0x** [comment]
Reopening the issue as it is still happening. In my experience it is now very intermittent and not nearly as severe as when this ticket was opened.

This would deserve to be investigated nonetheless.

**Comment by fyockm** [comment]
We are actively trying to debug, but having difficulty reproducing the `Blocked event loop` error. For those still seeing the issue, could you answer some questions to help us?

- What version of the extension you are using?
- What is your storage type (extension storage vs S3) and approximate storage size?
- Could you share some metrics about your data? i.e. how many users, groups, roles, etc do you have?
- What endpoints are causing the error? e.g. `/policy`, `/login`, group/roles management?

/cc @zxan1285

**Comment by gex** [comment]
still happens 10-15 times(!) a day with 80-100 active user on a us tenant.

- `What version of the extension you are using?`
  we added the extension on the extensions page, it's 2.4. i see a new version (2.5) on the extensions page but i didn't find any information about that in the [CHANGELOG](https://github.com/auth0/auth0-authorization-extension/blob/master/CHANGELOG.md) nor on the [releases page](https://github.com/auth0/auth0-authorization-extension/releases)
- `What is your storage type (extension storage vs S3) and approximate storage size?`
  extension
- `Could you share some metrics about your data?`
  100 users, 8 groups, 10 roles (across 3 applications), 62 permissions
- `What endpoints are causing the error?`
  always the login

we also got a promise back in q1 about a new, more integrated authorization solution with an estimated release in q3. are you still maintaining this extension or working on the new one only?

**Comment by simonwatt** [comment]
This has just happened for me on a project I have on UAT... 

version of extension: 2.5
storage type: webtask storage
metrics: about 100 users, but hardly any active logins. However, was hoping to deploy to production environment with over 20k users.
endpoint: pretty sure it's the login endpoint, but I can't easily tell looking at the logs

My authorization extension is configured to use Roles only (no groups or permissions), configuration only has enabled for: 'add roles to the user's token' and 'persist roles in the user's application metadata'

The main Auth0 log shows one error message with:
  "description": "Authorization Extension: ETIMEDOUT",

And a subsequent log a few minutes later (so I assume a second login attempt) with:
Type | Failed Exchange
Authorization Extension: Blocked event loop

Then a few minutes later login has started to work again, with no further issues... I can no longer reproduce but very hesitant to deploy to a production environment with intermittent issues like this.

**Comment by simonwatt** [comment]
Despite my comment above we ended up deploying to production environment. All had been working well for a month or so until this morning when some of our App logins (via auth0-cordova plugin) were hanging. I noticed in logs there are some instances with the Blocked event loop error:

```
{
  "date": "2018-12-02T22:35:01.235Z",
  "type": "fertft",
  "description": "Authorization Extension: Blocked event loop",
  "connection_id": "",
  "client_id": "[removed]",
  "client_name": "[removed]",
  "ip": "[removed]",
  "user_agent": "Mozilla/5.0 (iPhone; CPU iPhone OS 11_2_1 like Mac OS X) AppleWebKit/604.4.7 (KHTML, like Gecko) Mobile/15C153",
  "hostname": "[removed]",
  "user_id": "",
  "user_name": "",
  "log_id": "[removed]"
}
```
Additionally, when I tried to login to the Authorization extension section on the dashboard this morning, on one occasion I got the following:

```
{
  "code": 500,
  "error": "Script generated an unhandled asynchronous exception.",
  "details": "Error: Blocked event loop",
  "name": "Error",
  "message": "Blocked event loop",
  "stack": "Error: Blocked event loop\n    at <anonymous>:1:38\n    at nextTickCallbackWith0Args (node.js:489:9)\n    at process._tickDomainCallback (node.js:459:13)"
}
```

Logs this morning at similar times also include several `Authorization Extension: ETIMEDOUT` and `Authorization Extension: ESOCKETTIMEDOUT` errors when users are attempting to login.

All issues seem intermittent.

**Comment by 21robin12** [comment]
Seeing this intermittently on a US tenant. Extension version 2.5.

**Comment by gex** [comment]
@21robin12 did you find the changelog of version 2.5? we got some warning messages about the outdated user search v2 and a deadline (2018-11-13) to upgrade the authorization extension to 2.5 which uses the user search v3. when we asked about the changelog they couldn't provide anything and they told us they'll postpone the removal of v2. we are afraid to upgrade to 2.5 because it's impossible to downgrade if something goes wrong.

**Comment by 21robin12** [comment]
> @21robin12 did you find the changelog of version 2.5? we got some warning messages about the outdated user search v2 and a deadline (2018-11-13) to upgrade the authorization extension to 2.5 which uses the user search v3. when we asked about the changelog they couldn't provide anything and they told us they'll postpone the removal of v2. we are afraid to upgrade to 2.5 because it's impossible to downgrade if something goes wrong.

Haven't got the changelog I'm afraid

**Comment by lucasklaassen** [comment]
Running into the exact same issue in our staging account:
```
"error": {
      "message": "Authorization Extension: Blocked event loop",
      "oauthError": "unauthorized",
      "type": "oauth-authorization"
    }
```

**Comment by gex** [comment]
hey @rwtombaugh,

i reported these errors back in september (see [my comment](https://github.com/auth0/auth0-authorization-extension/issues/165#issuecomment-421377044) above) and i've checked the runtimes of all of our tenants and they're node 8. i don't even see the deprecated node 4 anywhere. so please don't close this issue because the migration won't solve the problem.

**Comment by gex** [comment]
@rwtombaugh we haven't changed anything since we created the 3 tenants for our 3 environments earlier this year. these tenants should be node 8 from the beginning.

would republishing the the rule help in this case?

**Comment by fyockm** [comment]
@gex please compare the `auth0-authz-extension` rule in your tenant(s) to https://github.com/auth0/auth0-authorization-extension/blob/master/server/lib/rules/authorize.js

Are they different? If so, what's different? And also then republishing could help.
